spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://34.9.116.242:3306/demo?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://35.226.206.30:3306/demo?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: demo
    password: DemoDockerMjk1!@#$


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true